#include "TestFramework.h"
#include "treecore/String.h"
#include "treecore/MT19937.h"

using namespace treecore;

const char* data[] = {
    "ZGXGQ",
    "WWPCO",
    "VDIPH",
    "HFNWA",
    "VWBHF",
    "VKOWI",
    "BCXBI",
    "LXTSH",
    "UXCVA",
    "HQVOY",
    "UWKJE",
    "GWUJX",
    "SDKKM",
    "BFGTB",
    "LHCWB",
    "BWESO",
    "JBJDC",
    "XFTNM",
    "KJZQL",
    "IUCQD",
    "BRRVZ",
    "HXCRV",
    "ZVDGH",
    "FDEJH",
    "GQMVS",
    "XZXFW",
    "VATEZ",
    "ABVHJ",
    "XVWCA",
    "NHLBB",
    "VDLWW",
    "LTBDB",
    "NITMY",
    "QRAKN",
    "JCZAM",
    "SKSSY",
    "UOISP",
    "NQVZH",
    "ZXECB",
    "FEXRN",
    "OQGJA",
    "CAAQM",
    "LHGTS",
    "CVBTQ",
    "UFEVP",
    "APMOS",
    "SHEGT",
    "KYLER",
    "FAOOA",
    "YZJZF",
    "LUVDS",
    "GIJWO",
    "SGIZL",
    "XOAIA",
    "CZDGB",
    "HTZHH",
    "TFEWM",
    "HIQLT",
    "KMNDO",
    "IJLCX",
    "QRWEF",
    "URZNL",
    "IINOQ",
    "IKNDN",
    "SVWVI",
    "YDXBA",
    "QLJYL",
    "UTDLR",
    "LWOBU",
    "CZWIH",
    "PEMKZ",
    "FUYCY",
    "DTLCP",
    "WURVD",
    "LVACF",
    "RGDBJ",
    "OVRIP",
    "SWAFE",
    "EXVHG",
    "NRBHU",
    "BDWGK",
    "BPKXN",
    "UZCAS",
    "VBFEB",
    "YLKWS",
    "MQIVZ",
    "GNAAO",
    "VSQZJ",
    "MSQRT",
    "ZYROH",
    "BGSLL",
    "BHNQB",
    "TMQTS",
    "BBRYG",
    "BYZWA",
    "EYVWQ",
    "PFKWA",
    "TUKLK",
    "CXEOJ",
    "RSJUT"
};

void TestFramework::content()
{
    MT19937 prng;

    for (int iter = 0; iter < 100; iter++)
    {
        String string_obj(data[iter]);
        int hash = string_obj.hashCode();
        printf("%s %d %d\n", string_obj.toRawUTF8(), hash, hash % 1000);
    }
}
